/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppResourcesRouteImport } from './routes/_app.resources'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMoreRouteImport } from './routes/_app.more'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCompanyRouteImport } from './routes/_app.company'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppAiIndexRouteImport } from './routes/_app.ai.index'
import { Route as AppProjectsNewRouteImport } from './routes/_app.projects.new'
import { Route as AppAiTaskRouteImport } from './routes/_app.ai.task'
import { Route as AppAiSummaryRouteImport } from './routes/_app.ai.summary'
import { Route as AppAiSettingsRouteImport } from './routes/_app.ai.settings'
import { Route as AppAiSearchRouteImport } from './routes/_app.ai.search'
import { Route as AppAiRiskRouteImport } from './routes/_app.ai.risk'
import { Route as AppAiProtocolRouteImport } from './routes/_app.ai.protocol'
import { Route as AppAiKnowledgeRouteImport } from './routes/_app.ai.knowledge'
import { Route as AppAiDailyReportRouteImport } from './routes/_app.ai.daily-report'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app.projects.$projectId.index'
import { Route as AppProjectsProjectIdEditRouteImport } from './routes/_app.projects.$projectId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanyRoute = AppCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiIndexRoute = AppAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAiRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAiTaskRoute = AppAiTaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiSummaryRoute = AppAiSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiSettingsRoute = AppAiSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiSearchRoute = AppAiSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiRiskRoute = AppAiRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiProtocolRoute = AppAiProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiKnowledgeRoute = AppAiKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiDailyReportRoute = AppAiDailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => AppAiRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdEditRoute =
  AppProjectsProjectIdEditRouteImport.update({
    id: '/projects/$projectId/edit',
    path: '/projects/$projectId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai': typeof AppAiRouteWithChildren
  '/company': typeof AppCompanyRoute
  '/dashboard': typeof AppDashboardRoute
  '/more': typeof AppMoreRoute
  '/profile': typeof AppProfileRoute
  '/resources': typeof AppResourcesRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/ai/daily-report': typeof AppAiDailyReportRoute
  '/ai/knowledge': typeof AppAiKnowledgeRoute
  '/ai/protocol': typeof AppAiProtocolRoute
  '/ai/risk': typeof AppAiRiskRoute
  '/ai/search': typeof AppAiSearchRoute
  '/ai/settings': typeof AppAiSettingsRoute
  '/ai/summary': typeof AppAiSummaryRoute
  '/ai/task': typeof AppAiTaskRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/ai/': typeof AppAiIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$projectId/edit': typeof AppProjectsProjectIdEditRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/company': typeof AppCompanyRoute
  '/dashboard': typeof AppDashboardRoute
  '/more': typeof AppMoreRoute
  '/profile': typeof AppProfileRoute
  '/resources': typeof AppResourcesRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/ai/daily-report': typeof AppAiDailyReportRoute
  '/ai/knowledge': typeof AppAiKnowledgeRoute
  '/ai/protocol': typeof AppAiProtocolRoute
  '/ai/risk': typeof AppAiRiskRoute
  '/ai/search': typeof AppAiSearchRoute
  '/ai/settings': typeof AppAiSettingsRoute
  '/ai/summary': typeof AppAiSummaryRoute
  '/ai/task': typeof AppAiTaskRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/ai': typeof AppAiIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$projectId/edit': typeof AppProjectsProjectIdEditRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/ai': typeof AppAiRouteWithChildren
  '/_app/company': typeof AppCompanyRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/ai/daily-report': typeof AppAiDailyReportRoute
  '/_app/ai/knowledge': typeof AppAiKnowledgeRoute
  '/_app/ai/protocol': typeof AppAiProtocolRoute
  '/_app/ai/risk': typeof AppAiRiskRoute
  '/_app/ai/search': typeof AppAiSearchRoute
  '/_app/ai/settings': typeof AppAiSettingsRoute
  '/_app/ai/summary': typeof AppAiSummaryRoute
  '/_app/ai/task': typeof AppAiTaskRoute
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/ai/': typeof AppAiIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$projectId/edit': typeof AppProjectsProjectIdEditRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/ai'
    | '/company'
    | '/dashboard'
    | '/more'
    | '/profile'
    | '/resources'
    | '/settings'
    | '/team'
    | '/ai/daily-report'
    | '/ai/knowledge'
    | '/ai/protocol'
    | '/ai/risk'
    | '/ai/search'
    | '/ai/settings'
    | '/ai/summary'
    | '/ai/task'
    | '/projects/new'
    | '/ai/'
    | '/projects/'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/company'
    | '/dashboard'
    | '/more'
    | '/profile'
    | '/resources'
    | '/settings'
    | '/team'
    | '/ai/daily-report'
    | '/ai/knowledge'
    | '/ai/protocol'
    | '/ai/risk'
    | '/ai/search'
    | '/ai/settings'
    | '/ai/summary'
    | '/ai/task'
    | '/projects/new'
    | '/ai'
    | '/projects'
    | '/projects/$projectId/edit'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_app/ai'
    | '/_app/company'
    | '/_app/dashboard'
    | '/_app/more'
    | '/_app/profile'
    | '/_app/resources'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/ai/daily-report'
    | '/_app/ai/knowledge'
    | '/_app/ai/protocol'
    | '/_app/ai/risk'
    | '/_app/ai/search'
    | '/_app/ai/settings'
    | '/_app/ai/summary'
    | '/_app/ai/task'
    | '/_app/projects/new'
    | '/_app/ai/'
    | '/_app/projects/'
    | '/_app/projects/$projectId/edit'
    | '/_app/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/company': {
      id: '/_app/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AppCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/': {
      id: '/_app/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AppAiIndexRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/task': {
      id: '/_app/ai/task'
      path: '/task'
      fullPath: '/ai/task'
      preLoaderRoute: typeof AppAiTaskRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/summary': {
      id: '/_app/ai/summary'
      path: '/summary'
      fullPath: '/ai/summary'
      preLoaderRoute: typeof AppAiSummaryRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/settings': {
      id: '/_app/ai/settings'
      path: '/settings'
      fullPath: '/ai/settings'
      preLoaderRoute: typeof AppAiSettingsRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/search': {
      id: '/_app/ai/search'
      path: '/search'
      fullPath: '/ai/search'
      preLoaderRoute: typeof AppAiSearchRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/risk': {
      id: '/_app/ai/risk'
      path: '/risk'
      fullPath: '/ai/risk'
      preLoaderRoute: typeof AppAiRiskRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/protocol': {
      id: '/_app/ai/protocol'
      path: '/protocol'
      fullPath: '/ai/protocol'
      preLoaderRoute: typeof AppAiProtocolRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/knowledge': {
      id: '/_app/ai/knowledge'
      path: '/knowledge'
      fullPath: '/ai/knowledge'
      preLoaderRoute: typeof AppAiKnowledgeRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/daily-report': {
      id: '/_app/ai/daily-report'
      path: '/daily-report'
      fullPath: '/ai/daily-report'
      preLoaderRoute: typeof AppAiDailyReportRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/edit': {
      id: '/_app/projects/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof AppProjectsProjectIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAiRouteChildren {
  AppAiDailyReportRoute: typeof AppAiDailyReportRoute
  AppAiKnowledgeRoute: typeof AppAiKnowledgeRoute
  AppAiProtocolRoute: typeof AppAiProtocolRoute
  AppAiRiskRoute: typeof AppAiRiskRoute
  AppAiSearchRoute: typeof AppAiSearchRoute
  AppAiSettingsRoute: typeof AppAiSettingsRoute
  AppAiSummaryRoute: typeof AppAiSummaryRoute
  AppAiTaskRoute: typeof AppAiTaskRoute
  AppAiIndexRoute: typeof AppAiIndexRoute
}

const AppAiRouteChildren: AppAiRouteChildren = {
  AppAiDailyReportRoute: AppAiDailyReportRoute,
  AppAiKnowledgeRoute: AppAiKnowledgeRoute,
  AppAiProtocolRoute: AppAiProtocolRoute,
  AppAiRiskRoute: AppAiRiskRoute,
  AppAiSearchRoute: AppAiSearchRoute,
  AppAiSettingsRoute: AppAiSettingsRoute,
  AppAiSummaryRoute: AppAiSummaryRoute,
  AppAiTaskRoute: AppAiTaskRoute,
  AppAiIndexRoute: AppAiIndexRoute,
}

const AppAiRouteWithChildren = AppAiRoute._addFileChildren(AppAiRouteChildren)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRouteWithChildren
  AppCompanyRoute: typeof AppCompanyRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMoreRoute: typeof AppMoreRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsProjectIdEditRoute: typeof AppProjectsProjectIdEditRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRouteWithChildren,
  AppCompanyRoute: AppCompanyRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMoreRoute: AppMoreRoute,
  AppProfileRoute: AppProfileRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsProjectIdEditRoute: AppProjectsProjectIdEditRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
